### PR TITLE
Fix postcss deprecation warning about `moveTo`.

### LINKED ISSUE #93: Node#moveTo was deprecated. Use Container#append.
Using 2.3.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #93 

/CC @ChristianMurphy

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, not sure why the tests fail. I'll try to have a look later unless someone else beats me to it.

**Comment by XhmikosR** [comment]
The problem seems to be `lossless: false` option of the parser, which does whitespace normalization. I'm not so familiar with the API so I guess I'll leave it to you @ChristianMurphy

**Comment by ChristianMurphy** [comment]
Thanks @XhmikosR!
I'll take a look.

**Comment by ChristianMurphy** [comment]
It appears that `append` adds a normalize step, that didn't exist in `moveTo`

https://github.com/postcss/postcss/blob/29a51b9c82bdf11f226e0d4196d18865d4bd10de/lib/node.es6#L241-L247
https://github.com/postcss/postcss/blob/5744739b161507ad3f9fea84b05fe78e86253c0b/lib/container.es6#L313-L319

I'll double check if there is a new configuration option to configure the append normalization.
More likely the tests will be updated and a SemVer major release will be cut.

**Comment by ChristianMurphy** [comment]
Tests have been updated to reflect normalization applied by `append`. :white_check_mark: 
Thanks again @XhmikosR! :bowing_man:

**Comment by XhmikosR** [comment]
Thanks!

**Comment by XhmikosR** [comment]
@ChristianMurphy: any chance for a new release?

**Comment by ChristianMurphy** [comment]
Sure, I was hoping to land #95 in the next release as well.
It looks like a `postcss-selector-parser` official version 3 release will take a while.
I'll cut a release a release now.

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
