### PR TITLE
Adds support for preserving selectors across media queries.

### LINKED ISSUE #6: Handle media queries
currently css like:

``` css
.module {
  color: green
}
.another-module {
  color: blue
}
@media (max-width: 600px) {
  .module {
    background: red
  }
  .another-module {
    background: yellow
  }
}
```

outputs

``` css
.module {
  color: green;
  background: red
}
.another-module {
  color: blue;
  background: yellow
}
@media (max-width: 600px) {
}
```

When media selectors usually mean that the two should not be combined

expected result would be

``` css
.module {
  color: green
}
.another-module {
  color: blue
}
@media (max-width: 600px) {
  .module {
    background: red
  }
  .another-module {
    background: yellow
  }
}
```

### PR DESCRIPTION
**Pull request by kristoferjoseph**
Resolves #6

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@kristoferjoseph it looks like Github is [unable to link](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) commit 3609c46 to you Github profile, would you like to ammend the commit? Or should I merge as is?

**Comment by kristoferjoseph** [comment]
Thanks for the heads up. I linked my work email and now it seems to be OK.
Was thinking the only issue with this PR is I am not stripping the query parameters used as the map key. This could potentially lead to duplicate keys because of whitespace. Let me add that before you merge please . 😀

**Comment by ChristianMurphy** [comment]
> I linked my work email and now it seems to be OK.

Awesome :+1: 

> Was thinking the only issue with this PR is I am not stripping the query parameters used as the map key. This could potentially lead to duplicate keys because of whitespace. Let me add that before you merge please . 

Sure

**Comment by kristoferjoseph** [comment]
OK should be good to go. 💕

**Comment by kristoferjoseph** [comment]
OK.
I will add two more tests.
I don't feel that this plugin should combine media queries though. I feel that this should be handled by something like [mq-packer](https://github.com/hail2u/node-css-mqpacker).
I personally use this plugin to dedupe at a module level and then merge mqs as a last step.

**Comment by ChristianMurphy** [comment]
> I will add two more tests.

Thanks Much!

> I don't feel that this plugin should combine media queries though. I feel that this should be handled by something like mq-packer.

Fair enough, rather than add the functionality, I made a note in #59 to update the README and reference MQPacker.

**Comment by ChristianMurphy** [comment]
Thanks @kristoferjoseph !

**Comment by kristoferjoseph** [comment]
My pleasure.

**Pull request merged**
